<?php
$a = new Lookup;
$b = $a -> getAll('post');
$c = $a -> getAll('employment_status');
$d = $a -> getAll('job_status');
$e = $a -> getAll('hokm_type');
$c['default'] = $d['default'] = $e['default'] = $b['default'] = '&#1575;&#1606;&#1578;&#1582;&#1575;&#1576;';
return array('add' => array('<table class="create"><tr><td>', 'hesab' => array('type' => 'text', 'in' => 'class="txt" maxlength="25"', 'validation' => array('required,maxLength[25]'), ), '</td><td>', 'bon' => array('type' => 'text', 'in' => 'class="txt" maxlength="16"', 'validation' => array('required,length[16]'), ), '</td><td>', 'bimeh' => array('type' => 'text', 'in' => 'class="txt" maxlength="25"', 'validation' => array('required,maxLength[25]'), ), '</td></tr><tr><td>', '<label>&#1578;&#1575;&#1585;&#1740;&#1582; &#1575;&#1587;&#1578;&#1582;&#1583;&#1575;&#1605;<span class="error">*</span></label>', 'd_employed' => array('decoration' => FALSE, 'type' => 'select', 'options' => 'days_of_month', 'validation' => array('required'), ), 'm_employed' => array('decoration' => FALSE, 'type' => 'select', 'options' => 'months_of_year', 'validation' => array('required'), ), 'y_employed' => array('decoration' => FALSE, 'type' => 'select', 'options' => 'years_1386_1393', 'validation' => array('required'), ), '</td><td><label>&#1593;&#1705;&#1587; &#1662;&#1585;&#1587;&#1606;&#1604;&#1740;<span class="error">*</span></label>', 'picture' => array('type' => 'file', 'decoration' => FALSE, 'in' => 'size="4"', 'showFieldErrorText' => TRUE), '</td></tr></table>', 'submit' => array('type' => 'submit', 'value' => '&#1605;&#1585;&#1581;&#1604;&#1607; &#1576;&#1593;&#1583;', 'in' => 'class="box"')), 'edit' => array('reference' => 'model', '<table style="background-color: #FFFFFF;
    border: 1px solid #E5E5E5;
    border-radius: 10px;
    box-shadow: 0 1px 2px rgba(0, 0, 0, 0.05);
    margin: 0 auto 20px;
    padding: 19px 29px 29px;
    width:90%; table-layout: fixed;"><tr><td>', 'clerk_number' => array('type' => 'text', 'in' => 'class="txt" maxLength="10"', 'validation' => array('required,number,maxLength[10]'), 'reference' => 'clerk_number', 'label' => '&#1588;&#1605;&#1575;&#1585;&#1607; &#1705;&#1575;&#1585;&#1605;&#1606;&#1583;&#1740;'), '</td><td>', 'hesab' => array('type' => 'text', 'in' => 'class="txt" maxlength="25"', 'validation' => array('required,maxLength[25]'), ), '</td><td>', 'bon' => array('type' => 'text', 'in' => 'class="txt" maxlength="16"', 'validation' => array('required,length[16]'), ), '</td></tr><tr><td>', 'bimeh' => array('type' => 'text', 'in' => 'class="txt" maxlength="25"', 'validation' => array('required,maxLength[25]'), ), '</td><td>', '<label>&#1578;&#1575;&#1585;&#1740;&#1582; &#1575;&#1587;&#1578;&#1582;&#1583;&#1575;&#1605;<span class="error">*</span></label>', 'd_employed' => array('decoration' => FALSE, 'type' => 'select', 'options' => 'days_of_month', 'validation' => array('required'), 'reference' => 'd'), 'm_employed' => array('decoration' => FALSE, 'type' => 'select', 'options' => 'months_of_year', 'validation' => array('required'), 'reference' => 'm'), 'y_employed' => array('decoration' => FALSE, 'type' => 'select', 'options' => 'years_1386_1393', 'validation' => array('required'), 'reference' => 'y'), ));
?>
